# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-warrior}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Bates"]
  s.date = %q{2009-09-25}
  s.default_executable = %q{rubywarrior}
  s.email = %q{ryan@railscasts.com}
  s.executables = ["rubywarrior"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/rubywarrior",
     "features/levels.feature",
     "features/profiles.feature",
     "features/step_definitions/common_steps.rb",
     "features/step_definitions/interaction_steps.rb",
     "features/support/env.rb",
     "features/support/mockio.rb",
     "features/towers.feature",
     "lib/ruby_warrior.rb",
     "lib/ruby_warrior/abilities/attack.rb",
     "lib/ruby_warrior/abilities/base.rb",
     "lib/ruby_warrior/abilities/bind.rb",
     "lib/ruby_warrior/abilities/direction_of.rb",
     "lib/ruby_warrior/abilities/direction_of_stairs.rb",
     "lib/ruby_warrior/abilities/distance.rb",
     "lib/ruby_warrior/abilities/explode.rb",
     "lib/ruby_warrior/abilities/feel.rb",
     "lib/ruby_warrior/abilities/health.rb",
     "lib/ruby_warrior/abilities/listen.rb",
     "lib/ruby_warrior/abilities/look.rb",
     "lib/ruby_warrior/abilities/pivot.rb",
     "lib/ruby_warrior/abilities/rescue.rb",
     "lib/ruby_warrior/abilities/rest.rb",
     "lib/ruby_warrior/abilities/shoot.rb",
     "lib/ruby_warrior/abilities/walk.rb",
     "lib/ruby_warrior/config.rb",
     "lib/ruby_warrior/core_additions.rb",
     "lib/ruby_warrior/floor.rb",
     "lib/ruby_warrior/game.rb",
     "lib/ruby_warrior/level.rb",
     "lib/ruby_warrior/level_loader.rb",
     "lib/ruby_warrior/player_generator.rb",
     "lib/ruby_warrior/position.rb",
     "lib/ruby_warrior/profile.rb",
     "lib/ruby_warrior/space.rb",
     "lib/ruby_warrior/tower.rb",
     "lib/ruby_warrior/turn.rb",
     "lib/ruby_warrior/ui.rb",
     "lib/ruby_warrior/units/archer.rb",
     "lib/ruby_warrior/units/base.rb",
     "lib/ruby_warrior/units/captive.rb",
     "lib/ruby_warrior/units/sludge.rb",
     "lib/ruby_warrior/units/thick_sludge.rb",
     "lib/ruby_warrior/units/warrior.rb",
     "lib/ruby_warrior/units/wizard.rb",
     "ruby-warrior.gemspec",
     "script/console",
     "spec/fixtures/short-tower/level_001.rb",
     "spec/fixtures/short-tower/level_002.rb",
     "spec/fixtures/walking_player.rb",
     "spec/ruby_warrior/abilities/attack_spec.rb",
     "spec/ruby_warrior/abilities/base_spec.rb",
     "spec/ruby_warrior/abilities/bind_spec.rb",
     "spec/ruby_warrior/abilities/direction_of_spec.rb",
     "spec/ruby_warrior/abilities/direction_of_stairs_spec.rb",
     "spec/ruby_warrior/abilities/distance_spec.rb",
     "spec/ruby_warrior/abilities/explode_spec.rb",
     "spec/ruby_warrior/abilities/feel_spec.rb",
     "spec/ruby_warrior/abilities/health_spec.rb",
     "spec/ruby_warrior/abilities/listen_spec.rb",
     "spec/ruby_warrior/abilities/look_spec.rb",
     "spec/ruby_warrior/abilities/pivot_spec.rb",
     "spec/ruby_warrior/abilities/rescue_spec.rb",
     "spec/ruby_warrior/abilities/rest_spec.rb",
     "spec/ruby_warrior/abilities/shoot_spec.rb",
     "spec/ruby_warrior/abilities/walk_spec.rb",
     "spec/ruby_warrior/floor_spec.rb",
     "spec/ruby_warrior/game_spec.rb",
     "spec/ruby_warrior/level_loader_spec.rb",
     "spec/ruby_warrior/level_spec.rb",
     "spec/ruby_warrior/player_generator_spec.rb",
     "spec/ruby_warrior/position_spec.rb",
     "spec/ruby_warrior/profile_spec.rb",
     "spec/ruby_warrior/space_spec.rb",
     "spec/ruby_warrior/tower_spec.rb",
     "spec/ruby_warrior/turn_spec.rb",
     "spec/ruby_warrior/ui_spec.rb",
     "spec/ruby_warrior/units/archer_spec.rb",
     "spec/ruby_warrior/units/base_spec.rb",
     "spec/ruby_warrior/units/captive_spec.rb",
     "spec/ruby_warrior/units/sludge_spec.rb",
     "spec/ruby_warrior/units/thick_sludge_spec.rb",
     "spec/ruby_warrior/units/warrior_spec.rb",
     "spec/ruby_warrior/units/wizard_spec.rb",
     "spec/spec_helper.rb",
     "templates/README.erb",
     "templates/player.rb",
     "tmp/.gitignore",
     "towers/beginner/level_001.rb",
     "towers/beginner/level_002.rb",
     "towers/beginner/level_003.rb",
     "towers/beginner/level_004.rb",
     "towers/beginner/level_005.rb",
     "towers/beginner/level_006.rb",
     "towers/beginner/level_007.rb",
     "towers/beginner/level_008.rb",
     "towers/beginner/level_009.rb",
     "towers/intermediate/level_001.rb",
     "towers/intermediate/level_002.rb",
     "towers/intermediate/level_003.rb",
     "towers/intermediate/level_004.rb",
     "towers/intermediate/level_005.rb",
     "towers/intermediate/level_006.rb"
  ]
  s.homepage = %q{http://github.com/ryanb/ruby-warrior}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Game written in Ruby for learning Ruby and artificial intelligence.}
  s.test_files = [
    "spec/fixtures/short-tower/level_001.rb",
     "spec/fixtures/short-tower/level_002.rb",
     "spec/fixtures/walking_player.rb",
     "spec/ruby_warrior/abilities/attack_spec.rb",
     "spec/ruby_warrior/abilities/base_spec.rb",
     "spec/ruby_warrior/abilities/bind_spec.rb",
     "spec/ruby_warrior/abilities/direction_of_spec.rb",
     "spec/ruby_warrior/abilities/direction_of_stairs_spec.rb",
     "spec/ruby_warrior/abilities/distance_spec.rb",
     "spec/ruby_warrior/abilities/explode_spec.rb",
     "spec/ruby_warrior/abilities/feel_spec.rb",
     "spec/ruby_warrior/abilities/health_spec.rb",
     "spec/ruby_warrior/abilities/listen_spec.rb",
     "spec/ruby_warrior/abilities/look_spec.rb",
     "spec/ruby_warrior/abilities/pivot_spec.rb",
     "spec/ruby_warrior/abilities/rescue_spec.rb",
     "spec/ruby_warrior/abilities/rest_spec.rb",
     "spec/ruby_warrior/abilities/shoot_spec.rb",
     "spec/ruby_warrior/abilities/walk_spec.rb",
     "spec/ruby_warrior/floor_spec.rb",
     "spec/ruby_warrior/game_spec.rb",
     "spec/ruby_warrior/level_loader_spec.rb",
     "spec/ruby_warrior/level_spec.rb",
     "spec/ruby_warrior/player_generator_spec.rb",
     "spec/ruby_warrior/position_spec.rb",
     "spec/ruby_warrior/profile_spec.rb",
     "spec/ruby_warrior/space_spec.rb",
     "spec/ruby_warrior/tower_spec.rb",
     "spec/ruby_warrior/turn_spec.rb",
     "spec/ruby_warrior/ui_spec.rb",
     "spec/ruby_warrior/units/archer_spec.rb",
     "spec/ruby_warrior/units/base_spec.rb",
     "spec/ruby_warrior/units/captive_spec.rb",
     "spec/ruby_warrior/units/sludge_spec.rb",
     "spec/ruby_warrior/units/thick_sludge_spec.rb",
     "spec/ruby_warrior/units/warrior_spec.rb",
     "spec/ruby_warrior/units/wizard_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
  end
end
